#--------------------------------------------------------
# Base stage
#--------------------------------------------------------
FROM debian:testing-slim

# Setup
ENV DEBIAN_FRONTEND=noninteractive

#--------------------------------------------------------
# Update & Install
#--------------------------------------------------------
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    gnupg \
    git \
    unzip \
    zip \
    tar \
    build-essential \
    cmake \
    ninja-build \
    pkg-config \
    gcc-mingw-w64-x86-64 \
    g++-mingw-w64-x86-64 \
    python3 \
    python3-pip \
    python3-setuptools \
    nodejs \
    gcovr \
    cppcheck \
    clang-format \
    && pip3 install --break-system-packages lizard \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/

WORKDIR /workspace
